### ISSUE TITLE
Full Example Code?

### ISSUE THREAD

**Issue by ghost** [topfullstack/nestjs-crud-mongoose#1]
Can you pls. post a full example that uses -- nestjsx/crud and typegoose?  Thanks in advance..,

**Comment by wxs77577** [comment]
Please refer to this: 
https://github.com/kpfromer/nestjs-typegoose#basic-usage

**Comment by ghost** [comment]
I was able to fix the issues and get it working.   But now run into an issue while executing where the client times-out waiting for a response.  @wxs77577 , Have you seen this issue?  Something's an issue because I can see that the code is being executed..,however it seems the method never returns.  Thoughts?
