### ISSUE TITLE
Find by Id ('/:id') isn't working.

### ISSUE THREAD

**Issue by ghost** [topfullstack/nestjs-crud-mongoose#2]
@wxs77577 , Can you pls. confirm that a search for one instance by id is working for you /  In my tests it isn't.., I have the 'crud' params on my controller set as,
`params: {
    id: {
        field: '_id',
        type: 'string',
        primary: true,
    },
  },`
Seems like I'm missing something obvious?  Also when i try with query params (?filter=_id||eq||<id>, it doesn't work either?  Your help is much appreciated.

**Comment by wxs77577** [comment]
use `id` instead `_id`

**Comment by ghost** [comment]
Thanks for the pointer.  I had `_id` defined as an attribute in my model which was the root-cause of the issue.  Correcting that and switching to `id` in the Crud definition addressed this. 

Appreciate the help and thanks for sharing this code.
